### ISSUE TITLE
TypeError issue with AWR1443

### ISSUE THREAD

**Issue by Saultes45** [ibaiGorordo/IWR1443-Read-Data-Python#12]
Hi,

First of all, thanks for the code!
I was able to run the code on a **raspberry pi 4** with **python 2.7**. I downloaded all the required libraries and I used **pyqt4**. I use an **AWR1443** mmWave radar bought very recently. The demo code was compiled with mmWave **SDK 2.1.0**.

When I start the code, a graph window appears on the bottom left corner. It has axes but no data are being plotted.

I logged the output of the console and put them in the file in the attachment. Since the same error is displayed on the console repeatedly, I put a single instance of the recurring error below (for more details please see there attached log file). 

It seems to be a **type error** between float and int: 
`TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('int32') with casting rule 'same_kind'` 

Here is a single instance:

> [22:53:16]  Ignored exception:
> 
>     |==============================>>
>     |  Traceback (most recent call last):
>     |    File "readData_IWR1443.py", line 323, in <module>
>     |      dataOk = update()
>     |    File "readData_IWR1443.py", line 289, in update
>     |      QtGui.QApplication.processEvents()
>     |    File "/home/pi/.local/lib/python2.7/site-packages/pyqtgraph/widgets/GraphicsView.py", line 161, in paintEvent
>     |      return QtGui.QGraphicsView.paintEvent(self, ev)
>     |    File "/home/pi/.local/lib/python2.7/site-packages/pyqtgraph/debug.py", line 93, in w
>     |      printExc('Ignored exception:')
>     |    --- exception caught here ---
>     |    File "/home/pi/.local/lib/python2.7/site-packages/pyqtgraph/debug.py", line 91, in w
>     |      func(*args, **kwds)
>     |    File "/home/pi/.local/lib/python2.7/site-packages/pyqtgraph/graphicsItems/ScatterPlotItem.py", line 1033, in paint
>     |      viewMask = self._maskAt(self.getViewBox().viewRect())
>     |    File "/home/pi/.local/lib/python2.7/site-packages/pyqtgraph/graphicsItems/ScatterPlotItem.py", line 1157, in _maskAt
>     |      w *= px
>     |  TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('int32') with casting rule 'same_kind'
>     |==============================<<

[log-1st-Feb-2021.txt](https://github.com/ibaiGorordo/IWR1443-Read-Data-Python-MMWAVE-SDK-1/files/5900546/log-1st-Feb-2021.txt)

Thanks in advance!

**Comment by ibaiGorordo** [comment]
It seems to be a problem with the variable types. I am not sure if it will fix your issue, but anyway, you should use Python3 with this repository.

Also, I will close your other issue, let me know how it goes with this issue.

Ibai

**Comment by Saultes45** [comment]
Thank you very much for your answer.
It is really great when the author of the code replies to the issues.

Tomorrow I will test and edit this message with the result. I will test:

- changing from python 2.7 to python 3.7 and 3.8
- using your code from another repo for SDK2.1 (despite the board name)

**Comment by ibaiGorordo** [comment]
No problem, and thanks for the patience.

I did not realize about the SDK version. Yes, you should definetely use the other repository. Sorry for the naming, I made this repository when the IWR1443 was only avaiable in the SDK version 1.

**Comment by Saultes45** [comment]
Sorry in advance for the long post...

### Hardware

- Raspberry pi 4
- AWR1443, with code compiled for SDK 2.1.0 

### Software

- python 2.7 and python 3.X
- pyqt 4

### Procedure

1. I used the official TI GUI on a win7 x64 PC with my `AWR1443` to test if it works properly
2. I used git clone to download all the following repository to the `/home/pi/` directory:
             - AWR1843-Read-Data-Python-MMWAVE-SDK-3-
             - AWR1642-Read-Data-Python-MMWAVE-SDK-2
             - IWR1443-Read-Data-Python-MMWAVE-SDK-1
3. I changed the parameters in the .conf file of each of the directory with the one
4. I opened a terminal and `cd` to the appropriate directory
5. I check that I have the latest pip version with `pip -V` and `pip3 -V` 
6. I checked I have the mentioned python libraries using `pip -ver` and `pip3 -ver`
7. I logged the output of the command line `python3 name_of_the_python_script.py` (python3.X)
8. I do the same for `python name_of_the_python_script.py` (python2.7)

### Result

When using python3, irrespective of the repository, I have (the name of the .py file and line n# are different each time, of course):

> Traceback (most recent call last):
>   File "readData_AWR1642.py", line 299, in <module>
>     CLIport, Dataport = serialConfig(configFileName)
>   File "readData_AWR1642.py", line 27, in serialConfig
>     CLIport = serial.Serial('/dev/ttyACM0', 115200)
> AttributeError: module 'serial' has no attribute 'Serial'


> Traceback (most recent call last):
>   File "readData_AWR1843.py", line 271, in <module>
>     CLIport, Dataport = serialConfig(configFileName)
>   File "readData_AWR1843.py", line 27, in serialConfig
>     CLIport = serial.Serial('/dev/ttyACM0', 115200)
> AttributeError: module 'serial' has no attribute 'Serial'

Which I think means the code was meant for python2.7 because the call to this library has changed.

Reference: https://stackoverflow.com/a/11404052

When I use python2.7, it seems I the code goes through. A figure always start at the bottom left on the monitor, the parameters are listed on the console (seems to be the same as in the file I modified). Then the code stops for 10s and then spits out some errors:

_Small version:_ 

> TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

_Complete version:_ (from AWR1642-Read-Data-Python-MMWAVE-SDK-2 but similar for all directories)

> % ***************************************************************
> % Created for SDK ver:01.02
> % Created using Visualizer ver:2.0.0.2
> % Frequency:77
> % Platform:xWR14xx
> % Scene Classifier:best_range_res
> % Azimuth Resolution(deg):15 + Elevation
> % Range Resolution(m):0.047
> % Maximum unambiguous Range(m):2.41
> % Maximum Radial Velocity(m/s):1
> % Radial velocity resolution(m/s):0.13
> % Frame Duration(msec):50
> % Range Detection Threshold (dB):15
> % Range Peak Grouping:disabled
> % Doppler Peak Grouping:disabled
> % Static clutter removal:enabled
> % ***************************************************************
> sensorStop
> flushCfg
> dfeDataOutputMode 1
> channelCfg 15 7 0
> adcCfg 2 1
> adcbufCfg 0 1 0 1
> profileCfg 0 77 267 7 57.14 0 0 70 1 240 4884 0 0 30
> chirpCfg 0 0 0 0 0 0 0 1
> chirpCfg 1 1 0 0 0 0 0 4
> chirpCfg 2 2 0 0 0 0 0 2
> frameCfg 0 2 16 0 100 1 0
> lowPower 0 1
> guiMonitor 1 0 0 0 0 1
> cfarCfg 0 2 8 4 3 0 1280
> peakGrouping 1 1 1 1 229
> multiObjBeamForming 1 0.5
> clutterRemoval 0
> calibDcRangeSig 0 -5 8 256
> compRangeBiasAndRxChanPhase 0.0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
> measureRangeBiasAndRxChanPhase 0 1.5 0.2
> CQRxSatMonitor 0 3 5 123 0
> CQSigImgMonitor 0 119 4
> analogMonitor 1 1
> sensorStart
> [13:58:06]  Ignored exception:
> 
>     |==============================>>
>     |  Traceback (most recent call last):
>     |    File "readData_AWR1642.py", line 325, in <module>
>     |      dataOk = update()
>     |    File "readData_AWR1642.py", line 291, in update
>     |      QtGui.QApplication.processEvents()
>     |    File "/home/pi/.local/lib/python2.7/site-packages/pyqtgraph/widgets/GraphicsView.py", line 161, in paintEvent
>     |      return QtGui.QGraphicsView.paintEvent(self, ev)
>     |    File "/home/pi/.local/lib/python2.7/site-packages/pyqtgraph/debug.py", line 93, in w
>     |      printExc('Ignored exception:')
>     |    --- exception caught here ---
>     |    File "/home/pi/.local/lib/python2.7/site-packages/pyqtgraph/debug.py", line 91, in w
>     |      func(*args, **kwds)
>     |    File "/home/pi/.local/lib/python2.7/site-packages/pyqtgraph/graphicsItems/ScatterPlotItem.py", line 1033, in paint
>     |      viewMask = self._maskAt(self.getViewBox().viewRect())
>     |    File "/home/pi/.local/lib/python2.7/site-packages/pyqtgraph/graphicsItems/ScatterPlotItem.py", line 1157, in _maskAt
>     |      w *= px
>     |  TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('int32') with casting rule 'same_kind'
>     |==============================<<
> [13:58:06]  Ignored exception:
> 
>     |==============================>>
>     |  Traceback (most recent call last):
>     |    File "readData_AWR1642.py", line 325, in <module>
>     |      dataOk = update()
>     |    File "readData_AWR1642.py", line 291, in update
>     |      QtGui.QApplication.processEvents()
>     |    File "/home/pi/.local/lib/python2.7/site-packages/pyqtgraph/widgets/GraphicsView.py", line 161, in paintEvent
>     |      return QtGui.QGraphicsView.paintEvent(self, ev)
>     |    File "/home/pi/.local/lib/python2.7/site-packages/pyqtgraph/debug.py", line 93, in w
>     |      printExc('Ignored exception:')
>     |    --- exception caught here ---
>     |    File "/home/pi/.local/lib/python2.7/site-packages/pyqtgraph/debug.py", line 91, in w
>     |      func(*args, **kwds)
>     |    File "/home/pi/.local/lib/python2.7/site-packages/pyqtgraph/graphicsItems/ScatterPlotItem.py", line 1033, in paint
>     |      viewMask = self._maskAt(self.getViewBox().viewRect())
>     |    File "/home/pi/.local/lib/python2.7/site-packages/pyqtgraph/graphicsItems/ScatterPlotItem.py", line 1157, in _maskAt
>     |      w *= px
>     |  TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('int32') with casting rule 'same_kind'
>     |==============================<<

**Comment by ibaiGorordo** [comment]
Thank you for the detailed report. Did you install pyserial in Python3? (pip3 install pyserial) My guess is that the problem you are having is a problem with pyserial, check this similar problem:
https://stackoverflow.com/questions/11403932/python-attributeerror-module-object-has-no-attribute-serial

Also, since you are using the mmWave SDK 2, then you just need to try the  AWR1642-Read-Data-Python-MMWAVE-SDK-2 repository, the others will give you errors later on because the data format from the radar is different.
