### ISSUE TITLE
Does required packages include installing sdk 3.0?

### ISSUE THREAD

**Issue by malikh36** [ibaiGorordo/IWR1443-Read-Data-Python#14]
Hi,
i am running the code the dataok always stays zero and no data is being gathered from the sensor , i wanted to know is there any other packages that needed to be installed other then following
numpy
pyqtgraph
pyserial

**Comment by ibaiGorordo** [comment]
Hi, which sdk version are you using? Each sdk version has a different configuration. So  if you are using the version 3, you should use this other repository:
https://github.com/ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-

**Comment by malikh36** [comment]
i have run the code in awr1843 with configuration file '6843.conf file' from the 'https://github.com/kirkster96/IWR6843-Read-Data-Python-MMWAVE-SDK'  but still same issue that no data is being collected.

i am using iwr6843ids osk module , i wanted to collect data from the sensor for doing further deep learning on it, i dont know about the sdk versions for the mmwave sensor , if you please give me short way out for doing this, like what are things i need to install to collect data after running the script.
Thanks for your reply

**Comment by ibaiGorordo** [comment]
I guess it is either a problem with the sdk version or that the xonfiguration file does not match. My recommendation is to use the mmwave demo  visualizer first to generate a get a working .config file. Also, that way you can test that the sdk version is the correcr one.

Once you have a working config file, you can replace the config file in this repository to run the python script.

**Comment by malikh36** [comment]
how can i generate .config file on mmwave demo visualizer , and also is there any way to run the mmwave demo visualizer on ubuntu,
one last question : after creating the .config file, do i need to install the sdk on my device to run the python script?

**Comment by ibaiGorordo** [comment]
- https://dev.ti.com/gallery/view/mmwave/mmWave_Demo_Visualizer
- Press the save "config to pc"
- No, you do not need the sdk installed, this repository only parses the data from the radar,  so you do not need the sdk.
