### ISSUE TITLE
Stop working after a few seconds

### ISSUE THREAD

**Issue by hfdzalv** [ibaiGorordo/IWR1443-Read-Data-Python#3]
Hi,,
I can see the data points but after a few seconds the frames received do not contain TLVs.

Do you know why this happen?

Thanks

Regards

**Comment by ibaiGorordo** [comment]
Hi,

Have you make a print on numTLVs and it prints 0? In that case try the code I have just uploaded (just removed the dataOK part in line 259).

If you have a different problem let me know more about your problem. 

- What SDK are you using?
- Until the data stops showing, does the data make sense?
- If it doesn't, try to print the frameNumber (to verify that the data is being parsed correctly)
- Also, print the value of byteVec and copy it here so I can check the program.

Best regards,
Ibai


-

**Comment by hfdzalv** [comment]
Hi,
I think that I solved it.
I have to add the following:

      `if idX > 0 and byteBufferLength>idX: (in line 259) and if startIdx and startIdx[0] < 
           byteBufferLength: (in line 139). 
`
Moreover, I also added:

     ` byteBuffer[byteBufferLength-startIdx[0]:] = np.zeros(len(byteBuffer[byteBufferLength- 
          startIdx[0]:]),dtype = 'uint8')  (in line 144)
      byteBuffer[byteBufferLength - shiftSize:] = np.zeros(len(byteBuffer[byteBufferLength - 
          shiftSize:]),dtype = 'uint8') (in line 264)`

Since when we are moving the data, there are some data that is replicated if it is not removed. 

Finally, I added the other cases (just in case they are considered):
          
            `elif tlv_type == MMWDEMO_UART_MSG_NOISE_PROFILE:
                idX += tlv_length
                
            elif tlv_type == MMWDEMO_UART_MSG_AZIMUT_STATIC_HEAD_MAP:
                idX += tlv_length
                
            elif tlv_type == MMWDEMO_UART_MSG_DOPPLER_HEAD_MAP:
                idX += tlv_length
                
            elif tlv_type == MMWDEMO_UART_MSG_STATS:
                idX += tlv_length
                
            elif tlv_type == MMWDEMO_UART_MSG_DETECTED_POINTS_SIDE_INFO:
                idX += tlv_length
              
            elif tlv_type == MMWDEMO_UART_MSG_MAX:
                idX += tlv_length 
`

Now, it works.

Many thanks

**Comment by ibaiGorordo** [comment]
I am glad it works. I will check your code and add update the program with your code.

Thank you for your feedback.
Best regards,
Ibai
