### ISSUE TITLE
AWR1642 not transmitting

### ISSUE THREAD

**Issue by maxentric-alevine** [ibaiGorordo/IWR1443-Read-Data-Python#7]
Hello, 

I am trying to live-stream raw ADC data using the AWR1642 and the MATLAB source you provided, however the device is not transmitting/receiving any data (see screenshot below). I believe this could be a firmware issue, which binary file are you running/which SDK are you using? Thanks in advance, your help is much appreciated!

Best,
-Amir 
!
![unnamed](https://user-images.githubusercontent.com/61162909/74681116-6c68ff80-5177-11ea-8c25-71bac6471323.jpg)
[unnamed](https://user-images.githubusercontent.com/61162909/74681104-64a95b00-5177-11ea-9511-b487febd06d1.jpg)

**Comment by ibaiGorordo** [comment]
Hello Amir,

Does the radar start measuring when you run the program? (the led DS3 should turn on). My guess is that the configuration file you are using is not the correct one for your firmware. What SDK is installed in your board?

Best regards,
Ibai

**Comment by maxentric-alevine** [comment]
Hi Ibai,

Thank you for your prompt response. Your guess was correct, I think had a
mismatched .cfg file and firmware version. Seeing information transmitting
now, thanks for your help!

Best,
-Amir

**Comment by ibaiGorordo** [comment]
I am glad to hear that. Let me know if you have any other problem.

I close this thread.
