### ISSUE TITLE
IWR1443BOOST: Receiving no data

### ISSUE THREAD

**Issue by Mirage1089** [ibaiGorordo/IWR1443-Read-Data-Python#9]
Hi,

I am not able to run your code perfectly. I am using,

mmwave_sdk_03_04_00_03
IWR1443BOOST (Using functional mode)

I have set the port number correctly and using your config file, just want to see it is working as you told.

In line 325, dataOk = update(), the value of dataOk is always 0.

Can you please tell me other than that you told in your documentation do I need to do anything more? Like do I need to load any image for this?

Best regards,
Nazmul

**Comment by ibaiGorordo** [comment]
Hi Nazmul,

The problem is that when I made this repository, the IWR1443 only worked with the SDK 1. If you are using the SDK 3, then use this repository:
https://github.com/ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-/blob/master/readData_AWR1843.py

Regards,
Ibai

**Comment by Mirage1089** [comment]
Hi Ibai,

Thank you very much for your fast reply.

I have just tried this repo code but the same issue.

Even I have just tried with IWR6843ISK but still the same issue.  I could run the mmwave demo visualizer with iwr6843isk. I think your code should run also iwr6843isk, right?

but nothing is running.

Best regards,
Nazmul

**Comment by Mirage1089** [comment]
Hi Ibai,

Thank you very very much.

I can now run your code with IWR6843ISK, that is what I needed.

The problem was I needed to restart the sensor before running it and had to use the code for sdk version 3.

Thank you again.

Best regards,
Nazmul
